/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon.stat.generator;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author Felix
 */
public class MainView extends javax.swing.JFrame {

    private final PokemonStatGenerator c;
    private final Model m;
    private final JRadioButton[] ntrPLUSArr;
    private final JRadioButton[] ntrMINUSArr;
    private final JLabel[] statAnz;
    private final JSpinner[] statCha;
    private final JTextField[] tbs;
    private ArrayList<StufenRechner> windows;

    
    /**
     * Creates new form MainView
     * @param c Controller
     * @param m Model
     */
    public MainView(PokemonStatGenerator c, Model m) {
        this.c = c;
        this.m = m;
        initComponents();
        
        windows = new ArrayList<>();
        
        ntrPLUS.add(ntrATKp);
        ntrPLUS.add(ntrDEFp);
        ntrPLUS.add(ntrSPAp);
        ntrPLUS.add(ntrSPDp);
        ntrPLUS.add(ntrINIp);
        ntrATKp.setSelected(true);
        
        ntrMINUS.add(ntrATKm);
        ntrMINUS.add(ntrDEFm);
        ntrMINUS.add(ntrSPAm);
        ntrMINUS.add(ntrSPDm);
        ntrMINUS.add(ntrINIm);
        ntrATKm.setSelected(true);
        
        JRadioButton[] placeholder1 = {ntrATKp, ntrDEFp, ntrSPAp, ntrSPDp, ntrINIp};
        ntrPLUSArr = placeholder1;
        JRadioButton[] placeholder2 = {ntrATKm, ntrDEFm, ntrSPAm, ntrSPDm, ntrINIm};
        ntrMINUSArr = placeholder2;
        
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
        
        statAnz = new JLabel[] {hpStat, atkStat, defStat, spaStat, spdStat, iniStat};
        statCha = new JSpinner[] {AtkStageSpinner, DefStageSpinner, SpAtkStageSpinner, SpDefStageSpinner, InitStageSpinner};
        
        tbs = new JTextField[] {hpTBEV, atkTBEV, defTBEV, spaTBEV, spdTBEV, iniTBEV};
        
        
        abilityDescTA.setWrapStyleWord(true);
        abilityDescTA.setLineWrap(true);
        abilityDescTA.setEditable(false);
        
        getImage();
        getEV();
        m.setStatChange(statCha);
        refreshTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ntrPLUS = new javax.swing.ButtonGroup();
        ntrMINUS = new javax.swing.ButtonGroup();
        pkmLB = new javax.swing.JLabel();
        generate = new javax.swing.JButton();
        stsPL = new javax.swing.JPanel();
        hpLBStat = new javax.swing.JLabel();
        atkLBStat = new javax.swing.JLabel();
        defLBStat = new javax.swing.JLabel();
        spaLBStat = new javax.swing.JLabel();
        spdLBStat = new javax.swing.JLabel();
        iniLBStat = new javax.swing.JLabel();
        hpStat = new javax.swing.JLabel();
        atkStat = new javax.swing.JLabel();
        defStat = new javax.swing.JLabel();
        spaStat = new javax.swing.JLabel();
        spdStat = new javax.swing.JLabel();
        iniStat = new javax.swing.JLabel();
        resetChange = new javax.swing.JButton();
        AtkStageSpinner = new javax.swing.JSpinner();
        DefStageSpinner = new javax.swing.JSpinner();
        SpAtkStageSpinner = new javax.swing.JSpinner();
        SpDefStageSpinner = new javax.swing.JSpinner();
        InitStageSpinner = new javax.swing.JSpinner();
        ivsPL = new javax.swing.JPanel();
        hpLBIV = new javax.swing.JLabel();
        hpSDIV = new javax.swing.JSlider();
        hpNrLBIV = new javax.swing.JLabel();
        atkLBIV = new javax.swing.JLabel();
        atkSDIV = new javax.swing.JSlider();
        atkNrLBIV = new javax.swing.JLabel();
        defLBIV = new javax.swing.JLabel();
        defSDIV = new javax.swing.JSlider();
        defNrLBIV = new javax.swing.JLabel();
        spaLBIV = new javax.swing.JLabel();
        spaSDIV = new javax.swing.JSlider();
        spaNrLBIV = new javax.swing.JLabel();
        spdLBIV = new javax.swing.JLabel();
        spdSDIV = new javax.swing.JSlider();
        spdNrLBIV = new javax.swing.JLabel();
        iniLBIV = new javax.swing.JLabel();
        iniSDIV = new javax.swing.JSlider();
        iniNrLBIV = new javax.swing.JLabel();
        randIV = new javax.swing.JButton();
        evsPL1 = new javax.swing.JPanel();
        hpLBEV = new javax.swing.JLabel();
        atkLBEV = new javax.swing.JLabel();
        defLBEV = new javax.swing.JLabel();
        spaLBEV = new javax.swing.JLabel();
        spdLBEV = new javax.swing.JLabel();
        iniLBEV = new javax.swing.JLabel();
        setZero = new javax.swing.JButton();
        totLB = new javax.swing.JLabel();
        totNrLB = new javax.swing.JLabel();
        randEV = new javax.swing.JButton();
        hpTBEV = new javax.swing.JTextField();
        atkTBEV = new javax.swing.JTextField();
        defTBEV = new javax.swing.JTextField();
        spaTBEV = new javax.swing.JTextField();
        spdTBEV = new javax.swing.JTextField();
        iniTBEV = new javax.swing.JTextField();
        abLB = new javax.swing.JLabel();
        abCB = new javax.swing.JComboBox<>();
        lvlLB = new javax.swing.JLabel();
        lvlSD = new javax.swing.JSlider();
        lvlNrLB = new javax.swing.JLabel();
        ntrPN = new javax.swing.JPanel();
        ntrATKp = new javax.swing.JRadioButton();
        ntrDEFp = new javax.swing.JRadioButton();
        ntrSPAp = new javax.swing.JRadioButton();
        ntrSPDp = new javax.swing.JRadioButton();
        ntrINIp = new javax.swing.JRadioButton();
        ntrATKm = new javax.swing.JRadioButton();
        ntrDEFm = new javax.swing.JRadioButton();
        ntrSPAm = new javax.swing.JRadioButton();
        ntrSPDm = new javax.swing.JRadioButton();
        ntrINIm = new javax.swing.JRadioButton();
        plusLB = new javax.swing.JLabel();
        minusLB = new javax.swing.JLabel();
        randNTR = new javax.swing.JButton();
        ntrLB = new javax.swing.JLabel();
        gif = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        evLB = new javax.swing.JLabel();
        evTXT = new javax.swing.JLabel();
        exp = new javax.swing.JLabel();
        newWindow = new javax.swing.JButton();
        pkmNameIDTF = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        langCB = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        abilityDescTA = new javax.swing.JTextArea();
        mainMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpenAttackSimMI = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyRPG: Pokémon Stat Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));

        pkmLB.setText("Pokémon:");

        generate.setText("Generate");
        generate.setEnabled(false);
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        stsPL.setBorder(javax.swing.BorderFactory.createTitledBorder("Stats"));
        stsPL.setToolTipText("");

        hpLBStat.setText("HP:");

        atkLBStat.setText("Atk:");

        defLBStat.setText("Def:");

        spaLBStat.setText("SpAtk:");

        spdLBStat.setText("SpDef:");

        iniLBStat.setText("Init.:");

        resetChange.setText("Set 0");
        resetChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetChangeActionPerformed(evt);
            }
        });

        AtkStageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, -6, 6, 1));
        AtkStageSpinner.setEnabled(false);
        AtkStageSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AtkStageChange(evt);
            }
        });

        DefStageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, -6, 6, 1));
        DefStageSpinner.setEnabled(false);
        DefStageSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                DefStageChange(evt);
            }
        });

        SpAtkStageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, -6, 6, 1));
        SpAtkStageSpinner.setEnabled(false);
        SpAtkStageSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpAtkStageChange(evt);
            }
        });

        SpDefStageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, -6, 6, 1));
        SpDefStageSpinner.setEnabled(false);
        SpDefStageSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpDefStageChange(evt);
            }
        });

        InitStageSpinner.setModel(new javax.swing.SpinnerNumberModel(0, -6, 6, 1));
        InitStageSpinner.setEnabled(false);
        InitStageSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                InitStageChange(evt);
            }
        });

        javax.swing.GroupLayout stsPLLayout = new javax.swing.GroupLayout(stsPL);
        stsPL.setLayout(stsPLLayout);
        stsPLLayout.setHorizontalGroup(
            stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stsPLLayout.createSequentialGroup()
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stsPLLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addComponent(atkLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(atkStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AtkStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addComponent(hpLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hpStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(defLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spaLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spdLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iniLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(stsPLLayout.createSequentialGroup()
                                        .addComponent(iniStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(InitStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(stsPLLayout.createSequentialGroup()
                                        .addComponent(defStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DefStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(stsPLLayout.createSequentialGroup()
                                        .addComponent(spaStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SpAtkStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(stsPLLayout.createSequentialGroup()
                                        .addComponent(spdStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(SpDefStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stsPLLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetChange)))
                .addContainerGap())
        );
        stsPLLayout.setVerticalGroup(
            stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stsPLLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpStat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atkLBStat)
                    .addComponent(atkStat)
                    .addComponent(AtkStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defStat)
                    .addComponent(defLBStat)
                    .addComponent(DefStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaStat)
                    .addComponent(spaLBStat)
                    .addComponent(SpAtkStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spdStat)
                    .addComponent(spdLBStat)
                    .addComponent(SpDefStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniStat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InitStageSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetChange)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ivsPL.setBorder(javax.swing.BorderFactory.createTitledBorder("IVs"));
        ivsPL.setToolTipText("");

        hpLBIV.setText("HP:");

        hpSDIV.setMaximum(31);
        hpSDIV.setValue(5);
        hpSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hpSDIVStateChanged(evt);
            }
        });

        hpNrLBIV.setText(""+hpSDIV.getValue());

        atkLBIV.setText("Atk:");

        atkSDIV.setMaximum(31);
        atkSDIV.setValue(5);
        atkSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                atkSDIVStateChanged(evt);
            }
        });

        atkNrLBIV.setText(""+atkSDIV.getValue());

        defLBIV.setText("Def:");

        defSDIV.setMaximum(31);
        defSDIV.setValue(5);
        defSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                defSDIVStateChanged(evt);
            }
        });

        defNrLBIV.setText(""+defSDIV.getValue());

        spaLBIV.setText("SpAtk:");

        spaSDIV.setMaximum(31);
        spaSDIV.setValue(5);
        spaSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spaSDIVStateChanged(evt);
            }
        });

        spaNrLBIV.setText(""+spaSDIV.getValue());

        spdLBIV.setText("SpDef:");

        spdSDIV.setMaximum(31);
        spdSDIV.setValue(5);
        spdSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spdSDIVStateChanged(evt);
            }
        });

        spdNrLBIV.setText(""+spdSDIV.getValue());

        iniLBIV.setText("Init.:");

        iniSDIV.setMaximum(31);
        iniSDIV.setValue(5);
        iniSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                iniSDIVStateChanged(evt);
            }
        });

        iniNrLBIV.setText(""+iniSDIV.getValue());

        randIV.setText("Random");
        randIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randIVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ivsPLLayout = new javax.swing.GroupLayout(ivsPL);
        ivsPL.setLayout(ivsPLLayout);
        ivsPLLayout.setHorizontalGroup(
            ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ivsPLLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addComponent(hpLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hpSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hpNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addComponent(atkLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atkSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atkNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spaLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spdLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addComponent(spaSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spaNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addComponent(defSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(defNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addComponent(spdSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spdNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(randIV)
                                    .addComponent(iniSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        ivsPLLayout.setVerticalGroup(
            ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ivsPLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hpNrLBIV)
                    .addComponent(hpSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atkLBIV)
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atkSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atkNrLBIV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defNrLBIV)
                            .addComponent(defLBIV)
                            .addComponent(defSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spaSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaLBIV)
                    .addComponent(spaNrLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spdSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spdLBIV)
                    .addComponent(spdNrLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniLBIV)
                    .addComponent(iniNrLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randIV))
        );

        evsPL1.setBorder(javax.swing.BorderFactory.createTitledBorder("EVs"));
        evsPL1.setToolTipText("");

        hpLBEV.setText("HP:");

        atkLBEV.setText("Atk:");

        defLBEV.setText("Def:");

        spaLBEV.setText("SpAtk:");

        spdLBEV.setText("SpDef:");

        iniLBEV.setText("Init.:");

        setZero.setText("Set 0");
        setZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setZeroActionPerformed(evt);
            }
        });

        totLB.setText("Total:");

        totNrLB.setText("0");

        randEV.setText("Random 50");
        randEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randEVActionPerformed(evt);
            }
        });

        hpTBEV.setText("0");

        atkTBEV.setText("0");

        defTBEV.setText("0");
        defTBEV.setToolTipText("");

        spaTBEV.setText("0");
        spaTBEV.setToolTipText("");

        spdTBEV.setText("0");

        iniTBEV.setText("0");

        javax.swing.GroupLayout evsPL1Layout = new javax.swing.GroupLayout(evsPL1);
        evsPL1.setLayout(evsPL1Layout);
        evsPL1Layout.setHorizontalGroup(
            evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evsPL1Layout.createSequentialGroup()
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(evsPL1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addComponent(spaLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spaTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spdLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iniLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spdTBEV)
                                    .addComponent(iniTBEV)))
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addComponent(hpLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hpTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atkLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(defLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atkTBEV, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(defTBEV)))))
                    .addGroup(evsPL1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setZero)
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addComponent(randEV)
                                .addGap(18, 18, 18)
                                .addComponent(totLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totNrLB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, Short.MAX_VALUE))
        );
        evsPL1Layout.setVerticalGroup(
            evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evsPL1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpLBEV)
                    .addComponent(hpTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atkLBEV)
                    .addComponent(atkTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defLBEV)
                    .addComponent(defTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaLBEV)
                    .addComponent(spaTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spdLBEV)
                    .addComponent(spdTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniLBEV)
                    .addComponent(iniTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(randEV)
                    .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totNrLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setZero)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        abLB.setText("Ability:");

        abCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        abCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                abilityStateChanged(evt);
            }
        });

        lvlLB.setText("Level:");

        lvlSD.setMinimum(1);
        lvlSD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lvlSDStateChanged(evt);
            }
        });

        lvlNrLB.setText(lvlSD.getValue()+"");

        ntrPN.setBorder(javax.swing.BorderFactory.createTitledBorder("Nature"));

        ntrATKp.setText("Atk");
        ntrATKp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrATKpActionPerformed(evt);
            }
        });

        ntrDEFp.setText("Def");
        ntrDEFp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrDEFpActionPerformed(evt);
            }
        });

        ntrSPAp.setText("SpAtk");
        ntrSPAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPApActionPerformed(evt);
            }
        });

        ntrSPDp.setText("SpDef");
        ntrSPDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPDpActionPerformed(evt);
            }
        });

        ntrINIp.setText("Init");
        ntrINIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrINIpActionPerformed(evt);
            }
        });

        ntrATKm.setText("Atk");
        ntrATKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrATKmActionPerformed(evt);
            }
        });

        ntrDEFm.setText("Def");
        ntrDEFm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrDEFmActionPerformed(evt);
            }
        });

        ntrSPAm.setText("SpAtk");
        ntrSPAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPAmActionPerformed(evt);
            }
        });

        ntrSPDm.setText("SpDef");
        ntrSPDm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPDmActionPerformed(evt);
            }
        });

        ntrINIm.setText("Init");
        ntrINIm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrINImActionPerformed(evt);
            }
        });

        plusLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plusLB.setText("-");
        plusLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        minusLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minusLB.setText("+");
        minusLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        randNTR.setText("Random");
        randNTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randNTRActionPerformed(evt);
            }
        });

        ntrLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ntrLB.setText("jLabel1");

        javax.swing.GroupLayout ntrPNLayout = new javax.swing.GroupLayout(ntrPN);
        ntrPN.setLayout(ntrPNLayout);
        ntrPNLayout.setHorizontalGroup(
            ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ntrPNLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(randNTR)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ntrDEFp)
                            .addComponent(ntrSPAp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ntrSPDp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ntrINIp)
                            .addComponent(ntrATKp)
                            .addComponent(minusLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ntrATKm)
                            .addComponent(ntrDEFm)
                            .addComponent(ntrSPAm)
                            .addComponent(ntrSPDm)
                            .addComponent(ntrINIm)
                            .addComponent(plusLB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(43, Short.MAX_VALUE))))
            .addGroup(ntrPNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ntrLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        ntrPNLayout.setVerticalGroup(
            ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ntrPNLayout.createSequentialGroup()
                .addComponent(ntrLB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minusLB)
                    .addComponent(plusLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addComponent(ntrATKm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrDEFm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPAm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPDm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrINIm))
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addComponent(ntrATKp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrDEFp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPAp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPDp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrINIp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(randNTR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gif.setBorder(javax.swing.BorderFactory.createTitledBorder("Icon"));
        gif.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        evLB.setText("EVs:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(evTXT)
                    .addComponent(evLB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(evLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evTXT)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        exp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exp.setBorder(javax.swing.BorderFactory.createTitledBorder("Exp."));
        exp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newWindow.setText("Open New Window");
        newWindow.setEnabled(false);
        newWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWindowActionPerformed(evt);
            }
        });

        pkmNameIDTF.setToolTipText("enter either the english name of a Pokémon or its national Pokédex ID");
        pkmNameIDTF.setName("pkmNameIDTF"); // NOI18N

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Pokémon Name");

        jLabel2.setText("Language Code");

        langCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "de", "en", "fr", "es", "it", "ko", "ja", "ja-Hrkt", "roomaji", "zh-Hant", "zh-Hans" }));
        langCB.setEnabled(false);
        langCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                langChange(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(234, 200));

        abilityDescTA.setColumns(20);
        abilityDescTA.setRows(5);
        abilityDescTA.setMaximumSize(new java.awt.Dimension(234, 200));
        jScrollPane1.setViewportView(abilityDescTA);

        mainMenuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMenu1.setText("File");

        OpenAttackSimMI.setText("Open AttackSim");
        OpenAttackSimMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenAttackSimMIAction(evt);
            }
        });
        jMenu1.add(OpenAttackSimMI);

        jMenuItem1.setText("Open PartyManager");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        mainMenuBar.add(jMenu1);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(pkmLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pkmNameIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(nameLabel)))
                        .addGap(119, 119, 119)
                        .addComponent(lvlLB)
                        .addGap(18, 18, 18)
                        .addComponent(lvlSD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lvlNrLB)
                        .addGap(18, 18, 18)
                        .addComponent(abLB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abCB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ivsPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(evsPL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(gif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(exp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(langCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newWindow)
                                .addGap(18, 18, 18)
                                .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(stsPL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ntrPN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pkmLB)
                        .addComponent(pkmNameIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loadButton))
                    .addComponent(lvlLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lvlNrLB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lvlSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(abLB)
                        .addComponent(abCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ivsPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(evsPL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ntrPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stsPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generate)
                    .addComponent(newWindow)
                    .addComponent(jLabel2)
                    .addComponent(langCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        m.statReset(statCha);
        int[] IVs = { hpSDIV.getValue(), atkSDIV.getValue(), defSDIV.getValue(), spaSDIV.getValue(), spdSDIV.getValue(), iniSDIV.getValue() };
        int[] EVs = getEVValues();
        
        m.calculateStats(EVs, IVs, lvlSD.getValue(), statAnz, exp);
        newWindow.setEnabled(true);
        for (JSpinner statCha1 : statCha) {
            statCha1.setEnabled(true);
        }
        
        refreshTotal();
    }//GEN-LAST:event_generateActionPerformed

    private void randIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randIVActionPerformed
        hpSDIV.setValue((int)(Math.random()*32));
        atkSDIV.setValue((int)(Math.random()*32));
        defSDIV.setValue((int)(Math.random()*32));
        spaSDIV.setValue((int)(Math.random()*32));
        spdSDIV.setValue((int)(Math.random()*32));
        iniSDIV.setValue((int)(Math.random()*32));
    }//GEN-LAST:event_randIVActionPerformed

    private void setZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setZeroActionPerformed
        for (JTextField t: tbs){
            t.setText("0");
        }
        refreshTotal();
    }//GEN-LAST:event_setZeroActionPerformed

    private void hpSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hpSDIVStateChanged
        this.hpNrLBIV.setText(hpSDIV.getValue()+"");
    }//GEN-LAST:event_hpSDIVStateChanged

    private void atkSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_atkSDIVStateChanged
        this.atkNrLBIV.setText(atkSDIV.getValue()+"");
    }//GEN-LAST:event_atkSDIVStateChanged

    private void defSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_defSDIVStateChanged
        this.defNrLBIV.setText(defSDIV.getValue()+"");
    }//GEN-LAST:event_defSDIVStateChanged

    private void spaSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spaSDIVStateChanged
        this.spaNrLBIV.setText(spaSDIV.getValue()+"");
    }//GEN-LAST:event_spaSDIVStateChanged

    private void spdSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spdSDIVStateChanged
        this.spdNrLBIV.setText(spdSDIV.getValue()+"");
    }//GEN-LAST:event_spdSDIVStateChanged

    private void iniSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_iniSDIVStateChanged
        this.iniNrLBIV.setText(iniSDIV.getValue()+"");
    }//GEN-LAST:event_iniSDIVStateChanged

    private void lvlSDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lvlSDStateChanged
        lvlNrLB.setText(lvlSD.getValue()+"");
    }//GEN-LAST:event_lvlSDStateChanged

    private void randNTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randNTRActionPerformed
        ntrPLUSArr[(int)((Math.random() * ntrPLUSArr.length))].setSelected(true);                                     
        ntrMINUSArr[(int)((Math.random() * ntrMINUSArr.length))].setSelected(true);
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_randNTRActionPerformed

    private void ntrATKpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrATKpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrATKpActionPerformed

    private void ntrDEFpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrDEFpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrDEFpActionPerformed

    private void ntrSPApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPApActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPApActionPerformed

    private void ntrSPDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPDpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPDpActionPerformed

    private void ntrINIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrINIpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrINIpActionPerformed

    private void ntrATKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrATKmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrATKmActionPerformed

    private void ntrDEFmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrDEFmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrDEFmActionPerformed

    private void ntrSPAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPAmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPAmActionPerformed

    private void ntrSPDmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPDmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPDmActionPerformed

    private void ntrINImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrINImActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrINImActionPerformed

    private void randEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randEVActionPerformed
        for (JTextField s : tbs){
            s.setText(""+(int)Math.floor(Math.random()*51));
        }
        refreshTotal();
    }//GEN-LAST:event_randEVActionPerformed

    private void newWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWindowActionPerformed
        Pokemon p = new Pokemon(m.getP());
        p.setStats(m.getStats().clone());
        p.setExp(exp.getText());
        p.setLevel(lvlSD.getValue());
        p.setAbility(abCB.getSelectedItem().toString());
        StufenRechner s = new StufenRechner(p);
        s.setVisible(true);
        windows.add(s);
    }//GEN-LAST:event_newWindowActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        loadButton.setEnabled(false);
        m.loadPokemon(pkmNameIDTF.getText());
        setAbilities();
        m.setAbility(abCB.getSelectedItem().toString());
        abilityDescTA.setText(m.getAbilityDesc());
        m.setName(nameLabel);
        getImage();
        getEV();
        generate.setEnabled(true);
        newWindow.setEnabled(false);                          
        loadButton.setEnabled(true);
        langCB.setEnabled(true);
    }//GEN-LAST:event_loadButtonActionPerformed

    private void resetChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetChangeActionPerformed
        m.statReset(statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_resetChangeActionPerformed

    private void AtkStageChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AtkStageChange
        m.setStatStage(0, (Integer) AtkStageSpinner.getValue());
        m.adjustStats(statAnz);
    }//GEN-LAST:event_AtkStageChange

    private void DefStageChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_DefStageChange
        m.setStatStage(1, (Integer) AtkStageSpinner.getValue());
        m.adjustStats(statAnz);
    }//GEN-LAST:event_DefStageChange

    private void SpAtkStageChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpAtkStageChange
        m.setStatStage(2, (Integer) AtkStageSpinner.getValue());
        m.adjustStats(statAnz);
    }//GEN-LAST:event_SpAtkStageChange

    private void SpDefStageChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpDefStageChange
        m.setStatStage(3, (Integer) AtkStageSpinner.getValue());
        m.adjustStats(statAnz);
    }//GEN-LAST:event_SpDefStageChange

    private void InitStageChange(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_InitStageChange
        m.setStatStage(4, (Integer) AtkStageSpinner.getValue());
        m.adjustStats(statAnz);
    }//GEN-LAST:event_InitStageChange

    private void langChange(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_langChange
        m.updateLanguage(langCB.getSelectedItem().toString());
        setAbilities();
        m.setName(nameLabel);
        m.setAbility(abCB.getSelectedItem().toString());
        abilityDescTA.setText(m.getAbilityDesc());
    }//GEN-LAST:event_langChange

    private void OpenAttackSimMIAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenAttackSimMIAction
        c.openAttackSim();
    }//GEN-LAST:event_OpenAttackSimMIAction

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        c.openPartyManager();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void abilityStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_abilityStateChanged
        m.setAbility(abCB.getSelectedItem().toString());
        abilityDescTA.setText(m.getAbilityDesc());
    }//GEN-LAST:event_abilityStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner AtkStageSpinner;
    private javax.swing.JSpinner DefStageSpinner;
    private javax.swing.JSpinner InitStageSpinner;
    private javax.swing.JMenuItem OpenAttackSimMI;
    private javax.swing.JSpinner SpAtkStageSpinner;
    private javax.swing.JSpinner SpDefStageSpinner;
    private javax.swing.JComboBox<String> abCB;
    private javax.swing.JLabel abLB;
    private javax.swing.JTextArea abilityDescTA;
    private javax.swing.JLabel atkLBEV;
    private javax.swing.JLabel atkLBIV;
    private javax.swing.JLabel atkLBStat;
    private javax.swing.JLabel atkNrLBIV;
    private javax.swing.JSlider atkSDIV;
    private javax.swing.JLabel atkStat;
    private javax.swing.JTextField atkTBEV;
    private javax.swing.JLabel defLBEV;
    private javax.swing.JLabel defLBIV;
    private javax.swing.JLabel defLBStat;
    private javax.swing.JLabel defNrLBIV;
    private javax.swing.JSlider defSDIV;
    private javax.swing.JLabel defStat;
    private javax.swing.JTextField defTBEV;
    private javax.swing.JLabel evLB;
    private javax.swing.JLabel evTXT;
    private javax.swing.JPanel evsPL1;
    private javax.swing.JLabel exp;
    private javax.swing.JButton generate;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel hpLBEV;
    private javax.swing.JLabel hpLBIV;
    private javax.swing.JLabel hpLBStat;
    private javax.swing.JLabel hpNrLBIV;
    private javax.swing.JSlider hpSDIV;
    private javax.swing.JLabel hpStat;
    private javax.swing.JTextField hpTBEV;
    private javax.swing.JLabel iniLBEV;
    private javax.swing.JLabel iniLBIV;
    private javax.swing.JLabel iniLBStat;
    private javax.swing.JLabel iniNrLBIV;
    private javax.swing.JSlider iniSDIV;
    private javax.swing.JLabel iniStat;
    private javax.swing.JTextField iniTBEV;
    private javax.swing.JPanel ivsPL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> langCB;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel lvlLB;
    private javax.swing.JLabel lvlNrLB;
    private javax.swing.JSlider lvlSD;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JLabel minusLB;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton newWindow;
    private javax.swing.JRadioButton ntrATKm;
    private javax.swing.JRadioButton ntrATKp;
    private javax.swing.JRadioButton ntrDEFm;
    private javax.swing.JRadioButton ntrDEFp;
    private javax.swing.JRadioButton ntrINIm;
    private javax.swing.JRadioButton ntrINIp;
    private javax.swing.JLabel ntrLB;
    private javax.swing.ButtonGroup ntrMINUS;
    private javax.swing.ButtonGroup ntrPLUS;
    private javax.swing.JPanel ntrPN;
    private javax.swing.JRadioButton ntrSPAm;
    private javax.swing.JRadioButton ntrSPAp;
    private javax.swing.JRadioButton ntrSPDm;
    private javax.swing.JRadioButton ntrSPDp;
    private javax.swing.JLabel pkmLB;
    private javax.swing.JTextField pkmNameIDTF;
    private javax.swing.JLabel plusLB;
    private javax.swing.JButton randEV;
    private javax.swing.JButton randIV;
    private javax.swing.JButton randNTR;
    private javax.swing.JButton resetChange;
    private javax.swing.JButton setZero;
    private javax.swing.JLabel spaLBEV;
    private javax.swing.JLabel spaLBIV;
    private javax.swing.JLabel spaLBStat;
    private javax.swing.JLabel spaNrLBIV;
    private javax.swing.JSlider spaSDIV;
    private javax.swing.JLabel spaStat;
    private javax.swing.JTextField spaTBEV;
    private javax.swing.JLabel spdLBEV;
    private javax.swing.JLabel spdLBIV;
    private javax.swing.JLabel spdLBStat;
    private javax.swing.JLabel spdNrLBIV;
    private javax.swing.JSlider spdSDIV;
    private javax.swing.JLabel spdStat;
    private javax.swing.JTextField spdTBEV;
    private javax.swing.JPanel stsPL;
    private javax.swing.JLabel totLB;
    private javax.swing.JLabel totNrLB;
    // End of variables declaration//GEN-END:variables

    /**
     * Loads sprite from URL and displays it
     */
    private void getImage() {
        URL url;
        try {
            url = new URL(m.getSprite());
            BufferedImage img = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(img);
            
            gif.setIcon(icon);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            System.out.println("Fehler bei Laden des Bildes. Überprüfe die Internetverbindung!");
        } catch (NullPointerException ex) {
            
        }
    }

    /**
     * Loads Effort Values (rewarded by defeating this Pokemon) from Model and displays them
     */
    private void getEV() {
        evTXT.setText(m.getEV());
    }
    
    private void refreshTotal(){
        int[] evs = getEVValues();
        int r = 0;
        
        for (int i = 0; i < evs.length; i++){
            r += evs[i];
        }
        
        totNrLB.setText(""+r);
    }
    
    /**
     * Returns the int-Array containing the Effort Values added to this Pokemon
     * 
     * @return int-Array of EVs [HP, Atk, Def, SpA, SpD, Ini]
     */
    private int[] getEVValues(){
        int [] r = new int[6];
        int i = 0;
        
        for (JTextField t : tbs){
            try {
            r[i] = Integer.parseInt(t.getText());
            } 
            catch (NumberFormatException e){
                javax.swing.JOptionPane.showMessageDialog(null, "Fehler bei Textkonvertierung!\nBitte nur Zahlen bei EVs eingeben!");
            }
            i++;
        }
        
        
        return r;
    }
    
    /**
     * Populates the Abilities Combobox with the Abilities loaded from the Model
     */
    void setAbilities(){
        javax.swing.DefaultComboBoxModel<String> mod = 
                new javax.swing.DefaultComboBoxModel<String>();
        for (String pa : m.getAbilities()){
            mod.addElement(pa);
        }
        abCB.setModel(mod);
    }
}
