/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon.stat.generator;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Felix
 */
public class PartyLevelManager extends javax.swing.JFrame {

    
    ArrayList<PartyMember> members;
    Model m;
    JLabel[] anz;
    
    /**
     * Creates new form PartyLevelManager
     */
    public PartyLevelManager() {
        
        m = new Model();
        members = new ArrayList<>();
        
        int [] igelavar = {14,27,30,24,15,29};
        double [] igelavarNAT = {0.9,1,1.1,1,1};
        members.add(new PartyMember(m.getPokemonbyDexNumber(156), "Daniel: Igelavar", igelavar,igelavarNAT));
        
        int [] zorua = {22,1,31,29,3,18};
        double [] zoruaNAT = {1,1,1,0.9,1.1};
        members.add(new PartyMember(m.getPokemonbyDexNumber(570), "Saskia: Zorua", zorua,zoruaNAT));
        
        int [] trasla = {9,26,7,28,24,20};
        double [] traslaNAT = {1,1,1,1,1};
        members.add(new PartyMember(m.getPokemonbyDexNumber(281), "Teo: Kirlia", trasla, traslaNAT));
        
        int[] stollunior = {22,22,2,8,25,9};
        double [] stolluniorNAT = {1,1.1,1,1,0.9};
        members.add(new PartyMember(m.getPokemonbyDexNumber(304), "Tristan: Stollunior", stollunior, stolluniorNAT));
        
        int[] evoli = {23,20,23,30,11,14};
        double [] evoliNAT = {1,0.9,1,1,1.1};
        members.add(new PartyMember(m.getPokemonbyDexNumber(133), "NPC: Evoli", evoli, evoliNAT));
        
        
        initComponents();
        
        for (PartyMember p : members){
            memberList.addItem(p.nickname);
        }
        
        JLabel[] zwi = {hpStat,atkStat,defStat,spaStat,spdStat,iniStat};
        anz = zwi;
        
        for (JLabel a : anz){
            a.setText("");
        }
        
        getImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberList = new javax.swing.JComboBox<>();
        hpEV = new javax.swing.JTextField();
        hp = new javax.swing.JLabel();
        atk = new javax.swing.JLabel();
        atkEV = new javax.swing.JTextField();
        def = new javax.swing.JLabel();
        defEV = new javax.swing.JTextField();
        spa = new javax.swing.JLabel();
        spaEV = new javax.swing.JTextField();
        spd = new javax.swing.JLabel();
        spdEV = new javax.swing.JTextField();
        ini = new javax.swing.JLabel();
        iniEV = new javax.swing.JTextField();
        evs = new javax.swing.JLabel();
        lv = new javax.swing.JLabel();
        hpStat = new javax.swing.JLabel();
        atkStat = new javax.swing.JLabel();
        defStat = new javax.swing.JLabel();
        spaStat = new javax.swing.JLabel();
        spdStat = new javax.swing.JLabel();
        iniStat = new javax.swing.JLabel();
        stat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        gif = new javax.swing.JLabel();
        levelSpinner = new javax.swing.JSpinner();

        setTitle("Party Manager");
        setResizable(false);

        memberList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chengedSelectedPokemon(evt);
            }
        });

        hpEV.setText("0");

        hp.setText("HP");

        atk.setText("Atk:");

        atkEV.setText("0");

        def.setText("Def:");

        defEV.setText("0");

        spa.setText("SpAtk:");

        spaEV.setText("0");

        spd.setText("SpDef:");

        spdEV.setText("0");

        ini.setText("Speed:");

        iniEV.setText("0");

        evs.setText("EVs");

        lv.setText("Level:");

        hpStat.setText("Stat HP");

        atkStat.setText("Stat Atk");

        defStat.setText("Stat Def");

        spaStat.setText("Stat SpA");

        spdStat.setText("Stat SpD");

        iniStat.setText("Stat Speed");

        stat.setText("Stat");

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        gif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gif.setBorder(javax.swing.BorderFactory.createTitledBorder("Icon"));
        gif.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        levelSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hp)
                                    .addComponent(atk)
                                    .addComponent(def))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(evs)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(atkEV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(hpEV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(defEV, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spa)
                                    .addComponent(spd)
                                    .addComponent(ini))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spdEV, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(spaEV, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(iniEV, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iniStat)
                            .addComponent(stat)
                            .addComponent(hpStat)
                            .addComponent(atkStat)
                            .addComponent(defStat)
                            .addComponent(spaStat)
                            .addComponent(spdStat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lv)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(levelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(memberList, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(hpEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hp)
                                    .addComponent(hpStat)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 9, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atkEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atk)
                            .addComponent(atkStat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(defEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(def)
                            .addComponent(defStat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spaEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spa)
                            .addComponent(spaStat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spdEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spd)
                            .addComponent(spdStat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ini)
                            .addComponent(jButton1)
                            .addComponent(iniEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniStat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(memberList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lv)
                            .addComponent(levelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(evs)
                            .addComponent(stat))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );

        hpStat.getAccessibleContext().setAccessibleName("hpStat");
        atkStat.getAccessibleContext().setAccessibleName("atkStat");
        defStat.getAccessibleContext().setAccessibleName("defStat");
        spaStat.getAccessibleContext().setAccessibleName("spaStat");
        spdStat.getAccessibleContext().setAccessibleName("spdStat");
        iniStat.getAccessibleContext().setAccessibleName("iniStat");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PartyMember pm = members.get(memberList.getSelectedIndex());
        int[] EVs = {Integer.parseInt(hpEV.getText()),Integer.parseInt(atkEV.getText()),
            Integer.parseInt(defEV.getText()),Integer.parseInt(spaEV.getText()),
            Integer.parseInt(spdEV.getText()),Integer.parseInt(iniEV.getText())};
        
        m.calculateStats(pm, EVs, pm.IVs, (int) levelSpinner.getValue(), anz, pm.natMUL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chengedSelectedPokemon(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chengedSelectedPokemon
        getImage();
    }//GEN-LAST:event_chengedSelectedPokemon

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartyLevelManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartyLevelManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartyLevelManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartyLevelManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PartyLevelManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atk;
    private javax.swing.JTextField atkEV;
    private javax.swing.JLabel atkStat;
    private javax.swing.JLabel def;
    private javax.swing.JTextField defEV;
    private javax.swing.JLabel defStat;
    private javax.swing.JLabel evs;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel hp;
    private javax.swing.JTextField hpEV;
    private javax.swing.JLabel hpStat;
    private javax.swing.JLabel ini;
    private javax.swing.JTextField iniEV;
    private javax.swing.JLabel iniStat;
    private javax.swing.JButton jButton1;
    private javax.swing.JSpinner levelSpinner;
    private javax.swing.JLabel lv;
    private javax.swing.JComboBox<String> memberList;
    private javax.swing.JLabel spa;
    private javax.swing.JTextField spaEV;
    private javax.swing.JLabel spaStat;
    private javax.swing.JLabel spd;
    private javax.swing.JTextField spdEV;
    private javax.swing.JLabel spdStat;
    private javax.swing.JLabel stat;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Loads sprite from URL and displays it
     */
    private void getImage() {
        PartyMember selectedPKM = members.get(memberList.getSelectedIndex());
        URL url;
        try {
            url = new URL(selectedPKM.getSprite());
            BufferedImage img = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(img);
            
            gif.setIcon(icon);
        } catch (MalformedURLException ex) {
            Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            System.out.println("Fehler bei Laden des Bildes. Überprüfe die Internetverbindung!");
        } catch (NullPointerException ex) {
            
        }
    }
}
