/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon.stat.generator;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSlider;
import javax.swing.JTextField;

/**
 *
 * @author Felix
 */
public class Window extends javax.swing.JFrame {

    private PokemonStatGenerator c;
    private Model m;
    private JRadioButton[] ntrPLUSArr;
    private JRadioButton[] ntrMINUSArr;
    private JLabel[] statAnz;
    private JLabel[] statCha;
    private JTextField[] tbs;
    private ArrayList<StufenRechner> windows;

    
    /**
     * Creates new form NewJFrame
     */
    public Window(PokemonStatGenerator c, Model m) {
        this.c = c;
        this.m = m;
        initComponents();
        
        windows = new ArrayList<StufenRechner>();
        
        ntrPLUS.add(ntrATKp);
        ntrPLUS.add(ntrDEFp);
        ntrPLUS.add(ntrSPAp);
        ntrPLUS.add(ntrSPDp);
        ntrPLUS.add(ntrINIp);
        ntrATKp.setSelected(true);
        
        ntrMINUS.add(ntrATKm);
        ntrMINUS.add(ntrDEFm);
        ntrMINUS.add(ntrSPAm);
        ntrMINUS.add(ntrSPDm);
        ntrMINUS.add(ntrINIm);
        ntrATKm.setSelected(true);
        
        JRadioButton[] placeholder1 = {ntrATKp, ntrDEFp, ntrSPAp, ntrSPDp, ntrINIp};
        ntrPLUSArr = placeholder1;
        JRadioButton[] placeholder2 = {ntrATKm, ntrDEFm, ntrSPAm, ntrSPDm, ntrINIm};
        ntrMINUSArr = placeholder2;
        
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
        
        statAnz = new JLabel[] {hpStat, atkStat, defStat, spaStat, spdStat, iniStat};
        statCha = new JLabel[] {atkChange, defChange, spaChange, spdChange, iniChange};
        
        tbs = new JTextField[] {hpTBEV, atkTBEV, defTBEV, spaTBEV, spdTBEV, iniTBEV};
        
        if (loadIcon.isSelected()){
            getImage();
        }
        getEV();
        m.setStatChange(statCha);
        refreshTotal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ntrPLUS = new javax.swing.ButtonGroup();
        ntrMINUS = new javax.swing.ButtonGroup();
        pkmLB = new javax.swing.JLabel();
        pkmCB = new javax.swing.JComboBox<>();
        generate = new javax.swing.JButton();
        stsPL = new javax.swing.JPanel();
        hpLBStat = new javax.swing.JLabel();
        atkLBStat = new javax.swing.JLabel();
        defLBStat = new javax.swing.JLabel();
        spaLBStat = new javax.swing.JLabel();
        spdLBStat = new javax.swing.JLabel();
        iniLBStat = new javax.swing.JLabel();
        hpStat = new javax.swing.JLabel();
        atkStat = new javax.swing.JLabel();
        defStat = new javax.swing.JLabel();
        spaStat = new javax.swing.JLabel();
        spdStat = new javax.swing.JLabel();
        iniStat = new javax.swing.JLabel();
        atkChange = new javax.swing.JLabel();
        defChange = new javax.swing.JLabel();
        spaChange = new javax.swing.JLabel();
        spdChange = new javax.swing.JLabel();
        iniChange = new javax.swing.JLabel();
        atkChangeM = new javax.swing.JButton();
        atkChangeP = new javax.swing.JButton();
        defChangeM = new javax.swing.JButton();
        defChangeP = new javax.swing.JButton();
        spaChangeM = new javax.swing.JButton();
        spaChangeP = new javax.swing.JButton();
        spdChangeM = new javax.swing.JButton();
        spdChangeP = new javax.swing.JButton();
        iniChangeM = new javax.swing.JButton();
        iniChangeP = new javax.swing.JButton();
        resetChange = new javax.swing.JButton();
        ivsPL = new javax.swing.JPanel();
        hpLBIV = new javax.swing.JLabel();
        hpSDIV = new javax.swing.JSlider();
        hpNrLBIV = new javax.swing.JLabel();
        atkLBIV = new javax.swing.JLabel();
        atkSDIV = new javax.swing.JSlider();
        atkNrLBIV = new javax.swing.JLabel();
        defLBIV = new javax.swing.JLabel();
        defSDIV = new javax.swing.JSlider();
        defNrLBIV = new javax.swing.JLabel();
        spaLBIV = new javax.swing.JLabel();
        spaSDIV = new javax.swing.JSlider();
        spaNrLBIV = new javax.swing.JLabel();
        spdLBIV = new javax.swing.JLabel();
        spdSDIV = new javax.swing.JSlider();
        spdNrLBIV = new javax.swing.JLabel();
        iniLBIV = new javax.swing.JLabel();
        iniSDIV = new javax.swing.JSlider();
        iniNrLBIV = new javax.swing.JLabel();
        randIV = new javax.swing.JButton();
        evsPL1 = new javax.swing.JPanel();
        hpLBEV = new javax.swing.JLabel();
        atkLBEV = new javax.swing.JLabel();
        defLBEV = new javax.swing.JLabel();
        spaLBEV = new javax.swing.JLabel();
        spdLBEV = new javax.swing.JLabel();
        iniLBEV = new javax.swing.JLabel();
        setZero = new javax.swing.JButton();
        totLB = new javax.swing.JLabel();
        totNrLB = new javax.swing.JLabel();
        randEV = new javax.swing.JButton();
        hpTBEV = new javax.swing.JTextField();
        atkTBEV = new javax.swing.JTextField();
        defTBEV = new javax.swing.JTextField();
        spaTBEV = new javax.swing.JTextField();
        spdTBEV = new javax.swing.JTextField();
        iniTBEV = new javax.swing.JTextField();
        abLB = new javax.swing.JLabel();
        abCB = new javax.swing.JComboBox<>();
        lvlLB = new javax.swing.JLabel();
        lvlSD = new javax.swing.JSlider();
        lvlNrLB = new javax.swing.JLabel();
        ntrPN = new javax.swing.JPanel();
        ntrATKp = new javax.swing.JRadioButton();
        ntrDEFp = new javax.swing.JRadioButton();
        ntrSPAp = new javax.swing.JRadioButton();
        ntrSPDp = new javax.swing.JRadioButton();
        ntrINIp = new javax.swing.JRadioButton();
        ntrATKm = new javax.swing.JRadioButton();
        ntrDEFm = new javax.swing.JRadioButton();
        ntrSPAm = new javax.swing.JRadioButton();
        ntrSPDm = new javax.swing.JRadioButton();
        ntrINIm = new javax.swing.JRadioButton();
        plusLB = new javax.swing.JLabel();
        minusLB = new javax.swing.JLabel();
        randNTR = new javax.swing.JButton();
        ntrLB = new javax.swing.JLabel();
        gif = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        evLB = new javax.swing.JLabel();
        evTXT = new javax.swing.JLabel();
        loadIcon = new javax.swing.JToggleButton();
        exp = new javax.swing.JLabel();
        newWindow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyRPG: Pokémon Stat Calculator");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 500));

        pkmLB.setText("Pokémon:");

        pkmCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pkmCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pkmCBItemStateChanged(evt);
            }
        });

        generate.setText("Generate");
        generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateActionPerformed(evt);
            }
        });

        stsPL.setBorder(javax.swing.BorderFactory.createTitledBorder("Stats"));
        stsPL.setToolTipText("");

        hpLBStat.setText("HP:");

        atkLBStat.setText("Atk:");

        defLBStat.setText("Def:");

        spaLBStat.setText("SpAtk:");

        spdLBStat.setText("SpDef:");

        iniLBStat.setText("Init.:");

        atkChange.setText("+6");
        atkChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        defChange.setText("+6");
        defChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        spaChange.setText("+6");
        spaChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        spdChange.setText("+6");
        spdChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        iniChange.setText("+6");
        iniChange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        atkChangeM.setText("-");
        atkChangeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atkChangeMActionPerformed(evt);
            }
        });

        atkChangeP.setText("+");
        atkChangeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atkChangePActionPerformed(evt);
            }
        });

        defChangeM.setText("-");
        defChangeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defChangeMActionPerformed(evt);
            }
        });

        defChangeP.setText("+");
        defChangeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defChangePActionPerformed(evt);
            }
        });

        spaChangeM.setText("-");
        spaChangeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaChangeMActionPerformed(evt);
            }
        });

        spaChangeP.setText("+");
        spaChangeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spaChangePActionPerformed(evt);
            }
        });

        spdChangeM.setText("-");
        spdChangeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spdChangeMActionPerformed(evt);
            }
        });

        spdChangeP.setText("+");
        spdChangeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spdChangePActionPerformed(evt);
            }
        });

        iniChangeM.setText("-");
        iniChangeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniChangeMActionPerformed(evt);
            }
        });

        iniChangeP.setText("+");
        iniChangeP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniChangePActionPerformed(evt);
            }
        });

        resetChange.setText("Set 0");
        resetChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stsPLLayout = new javax.swing.GroupLayout(stsPL);
        stsPL.setLayout(stsPLLayout);
        stsPLLayout.setHorizontalGroup(
            stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stsPLLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stsPLLayout.createSequentialGroup()
                        .addComponent(hpLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hpStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stsPLLayout.createSequentialGroup()
                        .addComponent(atkLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atkStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atkChange, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atkChangeM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(atkChangeP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stsPLLayout.createSequentialGroup()
                        .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spaLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spdLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addComponent(defStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(defChange, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(defChangeM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(defChangeP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addComponent(spaStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spaChange, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spaChangeM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(spaChangeP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addComponent(spdStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spdChange, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spdChangeM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(spdChangeP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addComponent(iniStat, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniChange, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(resetChange)
                                    .addGroup(stsPLLayout.createSequentialGroup()
                                        .addComponent(iniChangeM, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(iniChangeP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stsPLLayout.setVerticalGroup(
            stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stsPLLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpStat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atkChangeM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(atkLBStat)
                        .addComponent(atkStat)
                        .addComponent(atkChange)
                        .addComponent(atkChangeP)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defStat)
                    .addComponent(defLBStat)
                    .addComponent(defChange)
                    .addComponent(defChangeM)
                    .addComponent(defChangeP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaStat)
                    .addComponent(spaLBStat)
                    .addComponent(spaChange)
                    .addComponent(spaChangeM)
                    .addComponent(spaChangeP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spdStat)
                    .addComponent(spdLBStat)
                    .addComponent(spdChange)
                    .addComponent(spdChangeM)
                    .addComponent(spdChangeP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stsPLLayout.createSequentialGroup()
                        .addComponent(iniStat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stsPLLayout.createSequentialGroup()
                        .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(stsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(iniChangeP)
                                    .addComponent(iniChangeM)
                                    .addComponent(iniChange)))
                            .addGroup(stsPLLayout.createSequentialGroup()
                                .addComponent(iniLBStat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(resetChange))))
        );

        ivsPL.setBorder(javax.swing.BorderFactory.createTitledBorder("IVs"));
        ivsPL.setToolTipText("");

        hpLBIV.setText("HP:");

        hpSDIV.setMaximum(31);
        hpSDIV.setValue(5);
        hpSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                hpSDIVStateChanged(evt);
            }
        });

        hpNrLBIV.setText(""+hpSDIV.getValue());

        atkLBIV.setText("Atk:");

        atkSDIV.setMaximum(31);
        atkSDIV.setValue(5);
        atkSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                atkSDIVStateChanged(evt);
            }
        });

        atkNrLBIV.setText(""+atkSDIV.getValue());

        defLBIV.setText("Def:");

        defSDIV.setMaximum(31);
        defSDIV.setValue(5);
        defSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                defSDIVStateChanged(evt);
            }
        });

        defNrLBIV.setText(""+defSDIV.getValue());

        spaLBIV.setText("SpAtk:");

        spaSDIV.setMaximum(31);
        spaSDIV.setValue(5);
        spaSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spaSDIVStateChanged(evt);
            }
        });

        spaNrLBIV.setText(""+spaSDIV.getValue());

        spdLBIV.setText("SpDef:");

        spdSDIV.setMaximum(31);
        spdSDIV.setValue(5);
        spdSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spdSDIVStateChanged(evt);
            }
        });

        spdNrLBIV.setText(""+spdSDIV.getValue());

        iniLBIV.setText("Init.:");

        iniSDIV.setMaximum(31);
        iniSDIV.setValue(5);
        iniSDIV.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                iniSDIVStateChanged(evt);
            }
        });

        iniNrLBIV.setText(""+iniSDIV.getValue());

        randIV.setText("Random");
        randIV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randIVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ivsPLLayout = new javax.swing.GroupLayout(ivsPL);
        ivsPL.setLayout(ivsPLLayout);
        ivsPLLayout.setHorizontalGroup(
            ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ivsPLLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addComponent(hpLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hpSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hpNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addComponent(atkLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atkSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(atkNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spaLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spdLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iniLBIV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addComponent(spaSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spaNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addComponent(defSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(defNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addComponent(spdSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spdNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(ivsPLLayout.createSequentialGroup()
                                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(randIV)
                                    .addComponent(iniSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(iniNrLBIV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
        );
        ivsPLLayout.setVerticalGroup(
            ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ivsPLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hpNrLBIV)
                    .addComponent(hpSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hpLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atkLBIV)
                    .addGroup(ivsPLLayout.createSequentialGroup()
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(atkSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atkNrLBIV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defNrLBIV)
                            .addComponent(defLBIV)
                            .addComponent(defSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spaSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaLBIV)
                    .addComponent(spaNrLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spdSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spdLBIV)
                    .addComponent(spdNrLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ivsPLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniSDIV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniLBIV)
                    .addComponent(iniNrLBIV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(randIV))
        );

        evsPL1.setBorder(javax.swing.BorderFactory.createTitledBorder("EVs"));
        evsPL1.setToolTipText("");

        hpLBEV.setText("HP:");

        atkLBEV.setText("Atk:");

        defLBEV.setText("Def:");

        spaLBEV.setText("SpAtk:");

        spdLBEV.setText("SpDef:");

        iniLBEV.setText("Init.:");

        setZero.setText("Set 0");
        setZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setZeroActionPerformed(evt);
            }
        });

        totLB.setText("Total:");

        totNrLB.setText("0");

        randEV.setText("Random 50");
        randEV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randEVActionPerformed(evt);
            }
        });

        hpTBEV.setText("0");

        atkTBEV.setText("0");

        defTBEV.setText("0");
        defTBEV.setToolTipText("");

        spaTBEV.setText("0");
        spaTBEV.setToolTipText("");

        spdTBEV.setText("0");

        iniTBEV.setText("0");

        javax.swing.GroupLayout evsPL1Layout = new javax.swing.GroupLayout(evsPL1);
        evsPL1.setLayout(evsPL1Layout);
        evsPL1Layout.setHorizontalGroup(
            evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evsPL1Layout.createSequentialGroup()
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(evsPL1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addComponent(spaLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spaTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spdLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iniLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spdTBEV)
                                    .addComponent(iniTBEV)))
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addComponent(hpLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hpTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(atkLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(defLBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(atkTBEV, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(defTBEV)))))
                    .addGroup(evsPL1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(setZero)
                            .addGroup(evsPL1Layout.createSequentialGroup()
                                .addComponent(randEV)
                                .addGap(18, 18, 18)
                                .addComponent(totLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totNrLB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(12, 12, Short.MAX_VALUE))
        );
        evsPL1Layout.setVerticalGroup(
            evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evsPL1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hpLBEV)
                    .addComponent(hpTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atkLBEV)
                    .addComponent(atkTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defLBEV)
                    .addComponent(defTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaLBEV)
                    .addComponent(spaTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spdLBEV)
                    .addComponent(spdTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iniLBEV)
                    .addComponent(iniTBEV, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(randEV)
                    .addGroup(evsPL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(totNrLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(setZero)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        abLB.setText("Ability:");

        abCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lvlLB.setText("Level:");

        lvlSD.setMinimum(1);
        lvlSD.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                lvlSDStateChanged(evt);
            }
        });

        lvlNrLB.setText(lvlSD.getValue()+"");

        ntrPN.setBorder(javax.swing.BorderFactory.createTitledBorder("Nature"));

        ntrATKp.setText("Atk");
        ntrATKp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrATKpActionPerformed(evt);
            }
        });

        ntrDEFp.setText("Def");
        ntrDEFp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrDEFpActionPerformed(evt);
            }
        });

        ntrSPAp.setText("SpAtk");
        ntrSPAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPApActionPerformed(evt);
            }
        });

        ntrSPDp.setText("SpDef");
        ntrSPDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPDpActionPerformed(evt);
            }
        });

        ntrINIp.setText("Init");
        ntrINIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrINIpActionPerformed(evt);
            }
        });

        ntrATKm.setText("Atk");
        ntrATKm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrATKmActionPerformed(evt);
            }
        });

        ntrDEFm.setText("Def");
        ntrDEFm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrDEFmActionPerformed(evt);
            }
        });

        ntrSPAm.setText("SpAtk");
        ntrSPAm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPAmActionPerformed(evt);
            }
        });

        ntrSPDm.setText("SpDef");
        ntrSPDm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrSPDmActionPerformed(evt);
            }
        });

        ntrINIm.setText("Init");
        ntrINIm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntrINImActionPerformed(evt);
            }
        });

        plusLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plusLB.setText("-");
        plusLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        minusLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minusLB.setText("+");
        minusLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        randNTR.setText("Random");
        randNTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randNTRActionPerformed(evt);
            }
        });

        ntrLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ntrLB.setText("jLabel1");

        javax.swing.GroupLayout ntrPNLayout = new javax.swing.GroupLayout(ntrPN);
        ntrPN.setLayout(ntrPNLayout);
        ntrPNLayout.setHorizontalGroup(
            ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ntrPNLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(randNTR)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ntrDEFp)
                            .addComponent(ntrSPAp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ntrSPDp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ntrINIp)
                            .addComponent(ntrATKp)
                            .addComponent(minusLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ntrATKm)
                            .addComponent(ntrDEFm)
                            .addComponent(ntrSPAm)
                            .addComponent(ntrSPDm)
                            .addComponent(ntrINIm)
                            .addComponent(plusLB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(53, Short.MAX_VALUE))))
            .addGroup(ntrPNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ntrLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        ntrPNLayout.setVerticalGroup(
            ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ntrPNLayout.createSequentialGroup()
                .addComponent(ntrLB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minusLB)
                    .addComponent(plusLB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ntrPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addComponent(ntrATKm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrDEFm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPAm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPDm)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrINIm))
                    .addGroup(ntrPNLayout.createSequentialGroup()
                        .addComponent(ntrATKp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrDEFp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPAp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrSPDp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ntrINIp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(randNTR)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gif.setBorder(javax.swing.BorderFactory.createTitledBorder("Icon"));
        gif.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Info"));

        evLB.setText("EVs:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(evLB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(evTXT)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evLB)
                    .addComponent(evTXT))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        loadIcon.setText("Load Icon");
        loadIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadIconActionPerformed(evt);
            }
        });

        exp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exp.setBorder(javax.swing.BorderFactory.createTitledBorder("Exp."));
        exp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        newWindow.setText("Open New Window");
        newWindow.setEnabled(false);
        newWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(newWindow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ivsPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(evsPL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(loadIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gif, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ntrPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stsPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pkmLB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pkmCB, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(113, 113, 113)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lvlLB)
                                        .addGap(18, 18, 18)
                                        .addComponent(lvlSD, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lvlNrLB))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(abLB)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(abCB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pkmLB)
                        .addComponent(pkmCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lvlLB, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lvlSD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lvlNrLB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(abLB)
                            .addComponent(abCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ntrPN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stsPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(gif, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loadIcon)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ivsPL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(evsPL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generate)
                    .addComponent(newWindow))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateActionPerformed
        m.statReset(statCha);
        int[] IVs = { hpSDIV.getValue(), atkSDIV.getValue(), defSDIV.getValue(), spaSDIV.getValue(), spdSDIV.getValue(), iniSDIV.getValue() };
        int[] EVs = getEVValues();
        
        m.calculateStats(EVs, IVs, lvlSD.getValue(), pkmCB.getSelectedIndex(), statAnz, exp);
        newWindow.setEnabled(true);
        
        refreshTotal();
    }//GEN-LAST:event_generateActionPerformed

    private void randIVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randIVActionPerformed
        hpSDIV.setValue((int)(Math.random()*32));
        atkSDIV.setValue((int)(Math.random()*32));
        defSDIV.setValue((int)(Math.random()*32));
        spaSDIV.setValue((int)(Math.random()*32));
        spdSDIV.setValue((int)(Math.random()*32));
        iniSDIV.setValue((int)(Math.random()*32));
    }//GEN-LAST:event_randIVActionPerformed

    private void setZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setZeroActionPerformed
        for (JTextField t: tbs){
            t.setText("0");
        }
        refreshTotal();
    }//GEN-LAST:event_setZeroActionPerformed

    private void hpSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_hpSDIVStateChanged
        this.hpNrLBIV.setText(hpSDIV.getValue()+"");
    }//GEN-LAST:event_hpSDIVStateChanged

    private void atkSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_atkSDIVStateChanged
        this.atkNrLBIV.setText(atkSDIV.getValue()+"");
    }//GEN-LAST:event_atkSDIVStateChanged

    private void defSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_defSDIVStateChanged
        this.defNrLBIV.setText(defSDIV.getValue()+"");
    }//GEN-LAST:event_defSDIVStateChanged

    private void spaSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spaSDIVStateChanged
        this.spaNrLBIV.setText(spaSDIV.getValue()+"");
    }//GEN-LAST:event_spaSDIVStateChanged

    private void spdSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spdSDIVStateChanged
        this.spdNrLBIV.setText(spdSDIV.getValue()+"");
    }//GEN-LAST:event_spdSDIVStateChanged

    private void iniSDIVStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_iniSDIVStateChanged
        this.iniNrLBIV.setText(iniSDIV.getValue()+"");
    }//GEN-LAST:event_iniSDIVStateChanged

    private void lvlSDStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_lvlSDStateChanged
        lvlNrLB.setText(lvlSD.getValue()+"");
    }//GEN-LAST:event_lvlSDStateChanged

    private void pkmCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pkmCBItemStateChanged
        m.setAbilities(abCB, pkmCB.getSelectedIndex());
        if (loadIcon.isSelected()){
            getImage();
        } else {
            gif.setIcon(null);
        }
        getEV();
        newWindow.setEnabled(false);
    }//GEN-LAST:event_pkmCBItemStateChanged

    private void randNTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randNTRActionPerformed
        ntrPLUSArr[(int)((Math.random() * ntrPLUSArr.length))].setSelected(true);                                     
        ntrMINUSArr[(int)((Math.random() * ntrMINUSArr.length))].setSelected(true);
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_randNTRActionPerformed

    private void ntrATKpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrATKpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrATKpActionPerformed

    private void ntrDEFpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrDEFpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrDEFpActionPerformed

    private void ntrSPApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPApActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPApActionPerformed

    private void ntrSPDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPDpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPDpActionPerformed

    private void ntrINIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrINIpActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrINIpActionPerformed

    private void ntrATKmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrATKmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrATKmActionPerformed

    private void ntrDEFmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrDEFmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrDEFmActionPerformed

    private void ntrSPAmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPAmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPAmActionPerformed

    private void ntrSPDmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrSPDmActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrSPDmActionPerformed

    private void ntrINImActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntrINImActionPerformed
        ntrLB.setText(m.setNature(ntrPLUSArr, ntrMINUSArr));
    }//GEN-LAST:event_ntrINImActionPerformed

    private void loadIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadIconActionPerformed
        if (loadIcon.isSelected()){
            getImage();
        } else {
            gif.setIcon(null);
        }
    }//GEN-LAST:event_loadIconActionPerformed

    private void atkChangeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atkChangeMActionPerformed
        m.statFall(0,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_atkChangeMActionPerformed

    private void defChangeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defChangeMActionPerformed
        m.statFall(1,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_defChangeMActionPerformed

    private void spaChangeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaChangeMActionPerformed
        m.statFall(2,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_spaChangeMActionPerformed

    private void spdChangeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spdChangeMActionPerformed
        m.statFall(3,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_spdChangeMActionPerformed

    private void iniChangeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniChangeMActionPerformed
        m.statFall(4,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_iniChangeMActionPerformed

    private void atkChangePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atkChangePActionPerformed
        m.statRaise(0,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_atkChangePActionPerformed

    private void defChangePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defChangePActionPerformed
        m.statRaise(1,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_defChangePActionPerformed

    private void spaChangePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spaChangePActionPerformed
        m.statRaise(2,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_spaChangePActionPerformed

    private void spdChangePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spdChangePActionPerformed
        m.statRaise(3,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_spdChangePActionPerformed

    private void iniChangePActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniChangePActionPerformed
        m.statRaise(4,statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_iniChangePActionPerformed

    private void resetChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetChangeActionPerformed
        m.statReset(statCha);
        m.adjustStats(statAnz);
    }//GEN-LAST:event_resetChangeActionPerformed

    private void randEVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randEVActionPerformed
        for (JTextField s : tbs){
            s.setText(""+(int)Math.floor(Math.random()*51));
        }
        refreshTotal();
    }//GEN-LAST:event_randEVActionPerformed

    private void newWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWindowActionPerformed
        Pokemon p = m.getP(pkmCB.getSelectedIndex());
        Pokemon p1 = new Pokemon(p.getDexNr(), p.getDex(), p.getName(), p.getBaseHP(), p.getBaseATK(), p.getBaseDEF(), p.getBaseSPA(), p.getBaseSPD(), p.getBaseINI(), p.getAbilities(), p.getBaseXP(), p.getLvlEntw(), p.getEVs());
        p1.setStats(m.getStats().clone());
        p1.setExp(exp.getText());
        p1.setLevel(lvlSD.getValue());
        p1.setAbility(abCB.getSelectedItem().toString());
        StufenRechner s = new StufenRechner(p1);
        s.setVisible(true);
        windows.add(s);
    }//GEN-LAST:event_newWindowActionPerformed

    private void refreshTotal(){
        int[] evs = getEVValues();
        int r = 0;
        
        for (int i = 0; i < evs.length; i++){
            r += evs[i];
        }
        
        totNrLB.setText(""+r);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> abCB;
    private javax.swing.JLabel abLB;
    private javax.swing.JLabel atkChange;
    private javax.swing.JButton atkChangeM;
    private javax.swing.JButton atkChangeP;
    private javax.swing.JLabel atkLBEV;
    private javax.swing.JLabel atkLBIV;
    private javax.swing.JLabel atkLBStat;
    private javax.swing.JLabel atkNrLBIV;
    private javax.swing.JSlider atkSDIV;
    private javax.swing.JLabel atkStat;
    private javax.swing.JTextField atkTBEV;
    private javax.swing.JLabel defChange;
    private javax.swing.JButton defChangeM;
    private javax.swing.JButton defChangeP;
    private javax.swing.JLabel defLBEV;
    private javax.swing.JLabel defLBIV;
    private javax.swing.JLabel defLBStat;
    private javax.swing.JLabel defNrLBIV;
    private javax.swing.JSlider defSDIV;
    private javax.swing.JLabel defStat;
    private javax.swing.JTextField defTBEV;
    private javax.swing.JLabel evLB;
    private javax.swing.JLabel evTXT;
    private javax.swing.JPanel evsPL1;
    private javax.swing.JLabel exp;
    private javax.swing.JButton generate;
    private javax.swing.JLabel gif;
    private javax.swing.JLabel hpLBEV;
    private javax.swing.JLabel hpLBIV;
    private javax.swing.JLabel hpLBStat;
    private javax.swing.JLabel hpNrLBIV;
    private javax.swing.JSlider hpSDIV;
    private javax.swing.JLabel hpStat;
    private javax.swing.JTextField hpTBEV;
    private javax.swing.JLabel iniChange;
    private javax.swing.JButton iniChangeM;
    private javax.swing.JButton iniChangeP;
    private javax.swing.JLabel iniLBEV;
    private javax.swing.JLabel iniLBIV;
    private javax.swing.JLabel iniLBStat;
    private javax.swing.JLabel iniNrLBIV;
    private javax.swing.JSlider iniSDIV;
    private javax.swing.JLabel iniStat;
    private javax.swing.JTextField iniTBEV;
    private javax.swing.JPanel ivsPL;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton loadIcon;
    private javax.swing.JLabel lvlLB;
    private javax.swing.JLabel lvlNrLB;
    private javax.swing.JSlider lvlSD;
    private javax.swing.JLabel minusLB;
    private javax.swing.JButton newWindow;
    private javax.swing.JRadioButton ntrATKm;
    private javax.swing.JRadioButton ntrATKp;
    private javax.swing.JRadioButton ntrDEFm;
    private javax.swing.JRadioButton ntrDEFp;
    private javax.swing.JRadioButton ntrINIm;
    private javax.swing.JRadioButton ntrINIp;
    private javax.swing.JLabel ntrLB;
    private javax.swing.ButtonGroup ntrMINUS;
    private javax.swing.ButtonGroup ntrPLUS;
    private javax.swing.JPanel ntrPN;
    private javax.swing.JRadioButton ntrSPAm;
    private javax.swing.JRadioButton ntrSPAp;
    private javax.swing.JRadioButton ntrSPDm;
    private javax.swing.JRadioButton ntrSPDp;
    private javax.swing.JComboBox<String> pkmCB;
    private javax.swing.JLabel pkmLB;
    private javax.swing.JLabel plusLB;
    private javax.swing.JButton randEV;
    private javax.swing.JButton randIV;
    private javax.swing.JButton randNTR;
    private javax.swing.JButton resetChange;
    private javax.swing.JButton setZero;
    private javax.swing.JLabel spaChange;
    private javax.swing.JButton spaChangeM;
    private javax.swing.JButton spaChangeP;
    private javax.swing.JLabel spaLBEV;
    private javax.swing.JLabel spaLBIV;
    private javax.swing.JLabel spaLBStat;
    private javax.swing.JLabel spaNrLBIV;
    private javax.swing.JSlider spaSDIV;
    private javax.swing.JLabel spaStat;
    private javax.swing.JTextField spaTBEV;
    private javax.swing.JLabel spdChange;
    private javax.swing.JButton spdChangeM;
    private javax.swing.JButton spdChangeP;
    private javax.swing.JLabel spdLBEV;
    private javax.swing.JLabel spdLBIV;
    private javax.swing.JLabel spdLBStat;
    private javax.swing.JLabel spdNrLBIV;
    private javax.swing.JSlider spdSDIV;
    private javax.swing.JLabel spdStat;
    private javax.swing.JTextField spdTBEV;
    private javax.swing.JPanel stsPL;
    private javax.swing.JLabel totLB;
    private javax.swing.JLabel totNrLB;
    // End of variables declaration//GEN-END:variables

    javax.swing.JComboBox<String> getPkmCB() {
        return pkmCB;
    }
    
    javax.swing.JComboBox<String> getabCB() {
        return abCB;
    }

    private void getImage() {
        URL url;
        try {
            url = new URL(m.getDex(pkmCB.getSelectedIndex()));
            BufferedImage img = ImageIO.read(url);
            ImageIcon icon = new ImageIcon(img);
            
            gif.setIcon(icon);
        } catch (MalformedURLException ex) {
            Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            System.out.println("Fehler bei Laden des Bildes. Überprüfe die Internetverbindung!");
        }
    }

    private void getEV() {
        evTXT.setText(m.getEV(pkmCB.getSelectedIndex()));
    }
    
    private int[] getEVValues(){
        int [] r = new int[6];
        int i = 0;
        
        for (JTextField t : tbs){
            try {
            r[i] = Integer.parseInt(t.getText());
            } 
            catch (NumberFormatException e){
                javax.swing.JOptionPane.showMessageDialog(null, "Fehler bei Textkonvertierung!\nBitte nur Zahlen bei EVs eingeben!");
            }
            i++;
        }
        
        
        return r;
    }
}
