/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokemon.attack.simulator;

import javax.swing.JOptionPane;

/**
 *
 * @author Felix
 */
public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        lb_levelzahl.setText(""+sld_level.getValue());
    }

    double f2, ap, dp, af, zf, bs, z, itf;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        p_f1 = new javax.swing.JPanel();
        cb_brt = new javax.swing.JCheckBox();
        cb_rl = new javax.swing.JCheckBox();
        combo_sr = new javax.swing.JComboBox<>();
        lb_sr = new javax.swing.JLabel();
        cb_ff = new javax.swing.JCheckBox();
        p_f2 = new javax.swing.JPanel();
        tf_f2 = new javax.swing.JTextField();
        p_f3 = new javax.swing.JPanel();
        cb_fkf = new javax.swing.JCheckBox();
        cb_eg = new javax.swing.JCheckBox();
        cb_a = new javax.swing.JCheckBox();
        cb_b = new javax.swing.JCheckBox();
        p_basisinfo = new javax.swing.JPanel();
        sld_level = new javax.swing.JSlider();
        lb_level = new javax.swing.JLabel();
        lb_levelzahl = new javax.swing.JLabel();
        tf_ap = new javax.swing.JTextField();
        lb_ap = new javax.swing.JLabel();
        lb_dp = new javax.swing.JLabel();
        tf_dp = new javax.swing.JTextField();
        combo_voll = new javax.swing.JComboBox<>();
        lb_sr1 = new javax.swing.JLabel();
        lb_z = new javax.swing.JLabel();
        tf_z = new javax.swing.JTextField();
        lb_stab = new javax.swing.JLabel();
        combo_stab = new javax.swing.JComboBox<>();
        lb_typ2 = new javax.swing.JLabel();
        lb_typ1 = new javax.swing.JLabel();
        combo_typ2 = new javax.swing.JComboBox<>();
        combo_typ1 = new javax.swing.JComboBox<>();
        lb_typ3 = new javax.swing.JLabel();
        combo_typ3 = new javax.swing.JComboBox<>();
        p_schadeninfo = new javax.swing.JPanel();
        cb_rh = new javax.swing.JCheckBox();
        lb_basisschaden = new javax.swing.JLabel();
        tf_angrf = new javax.swing.JTextField();
        cb_lv = new javax.swing.JCheckBox();
        cb_ls = new javax.swing.JCheckBox();
        cb_nm = new javax.swing.JCheckBox();
        lb_angrf = new javax.swing.JLabel();
        lb_zielf = new javax.swing.JLabel();
        tf_basisschaden = new javax.swing.JTextField();
        tf_zielf = new javax.swing.JTextField();
        lb_itemf = new javax.swing.JLabel();
        tf_itemf = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btn_calc = new javax.swing.JButton();
        lb_erg = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jCheckBox3.setText("jCheckBox3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DnP Angriffrechner");

        p_f1.setBorder(javax.swing.BorderFactory.createTitledBorder("F1"));

        cb_brt.setText("BRT");
        cb_brt.setToolTipText("aktivieren, wenn Angreifer brennt und physischen Schaden austeilt");

        cb_rl.setText("RL");
        cb_rl.setToolTipText("<html>\nankreuzen, wenn Reflektor (phyischer Schaden) oder Lichtschild (spezieller Schaden) aktiviert ist<br>\nnicht ankreuzen, wenn der Angreifer einen Volltreffer landet\n</html>");

        combo_sr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0.5", "1.5" }));
        combo_sr.setToolTipText("starke Sonneneinstrahlung bzw. starker Regen\n\nWenn Sonne: Feuer-Attacke 1,5 - Wasser-Attacke 0,5\nWenn Regen: Wasser-Attacke 1,5 - Feuer-Attacke 0,5\n\nansonsten: 1");

        lb_sr.setText("SR");

        cb_ff.setText("FF");
        cb_ff.setToolTipText("nur ankreuzen, wenn Angreifer Feuerfänger hat und davor von einer Feuer-Attacke getroffen wurde");

        javax.swing.GroupLayout p_f1Layout = new javax.swing.GroupLayout(p_f1);
        p_f1.setLayout(p_f1Layout);
        p_f1Layout.setHorizontalGroup(
            p_f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_f1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_f1Layout.createSequentialGroup()
                        .addComponent(cb_brt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_ff))
                    .addGroup(p_f1Layout.createSequentialGroup()
                        .addComponent(cb_rl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_sr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_sr, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        p_f1Layout.setVerticalGroup(
            p_f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_f1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_brt)
                    .addComponent(cb_ff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p_f1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_sr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sr)
                    .addComponent(cb_rl))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        p_f2.setBorder(javax.swing.BorderFactory.createTitledBorder("F2"));
        p_f2.setToolTipText("<html>\nWenn Angreifer Lebenorb trägt: 1,3<br>\nWenn Angreifer Metronom hält: siehe DM-Doc<br>\nWenn Angriff Egotrip: ist 1,5<br>\n<br>\nWenn Egotrip eingesetzt wird und der Angreifer eines der genannten Items trägt: 1,5 * Itemwert");

        javax.swing.GroupLayout p_f2Layout = new javax.swing.GroupLayout(p_f2);
        p_f2.setLayout(p_f2Layout);
        p_f2Layout.setHorizontalGroup(
            p_f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_f2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_f2)
                .addContainerGap())
        );
        p_f2Layout.setVerticalGroup(
            p_f2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_f2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tf_f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_f3.setBorder(javax.swing.BorderFactory.createTitledBorder("F3"));

        cb_fkf.setText("FKF");
        cb_fkf.setToolTipText("<html>\nankreuzen, wenn alles zutrifft:<br><br>\ndas Ziel eine der folgenden Fähigkeiten: Felskern, Filter<br>\ndie Attacke ist sehr effektiv");

        cb_eg.setText("EG");
        cb_eg.setToolTipText("<html>\nankreuzen, wenn folgendes Zutrifft:<br>\n<br>\nDer Angreifer trägt das Item Expertengurt<br>\nDer Angriff ist sehr effektiv");

        cb_a.setText("A");
        cb_a.setToolTipText("<html>\nankreuzen, wenn folgendes zutrifft:<br>\n<br>\nDer Angreifer hat die Fähigkeit Aufwertung<br>\nDie Attacke ist nicht sehr effektiv");

        cb_b.setText("B");
        cb_b.setToolTipText("ankreuzen, wenn das Ziel eine schadensreduzierende Beere trägt");

        javax.swing.GroupLayout p_f3Layout = new javax.swing.GroupLayout(p_f3);
        p_f3.setLayout(p_f3Layout);
        p_f3Layout.setHorizontalGroup(
            p_f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_f3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_fkf)
                    .addComponent(cb_eg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_b)
                    .addComponent(cb_a))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_f3Layout.setVerticalGroup(
            p_f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_f3Layout.createSequentialGroup()
                .addGroup(p_f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_fkf)
                    .addComponent(cb_a))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_f3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_b)
                    .addComponent(cb_eg))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        p_basisinfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Basisinfo"));

        sld_level.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sld_levelStateChanged(evt);
            }
        });

        lb_level.setText("Level");

        lb_levelzahl.setText("100");

        tf_ap.setToolTipText("Den Attacken-Stat vom Anwender, mit Formel auf DM-Doc ausrechnen");

        lb_ap.setText("AP");

        lb_dp.setText("DP");

        tf_dp.setToolTipText("Den Verteidigungs-Stat vom Ziel, mit Formel auf DM-Doc ausrechnen");

        combo_voll.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2" }));
        combo_voll.setToolTipText("starke Sonneneinstrahlung bzw. starker Regen\n\nWenn Sonne: Feuer-Attacke 1,5 - Wasser-Attacke 0,5\nWenn Regen: Wasser-Attacke 1,5 - Feuer-Attacke 0,5\n\nansonsten: 1");

        lb_sr1.setText("Volltreffer");

        lb_z.setText("Z");

        tf_z.setToolTipText("2 d8-1 würfeln und hier eintragen");

        lb_stab.setText("STAB");

        combo_stab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "1.5", "2" }));
        combo_stab.setToolTipText("starke Sonneneinstrahlung bzw. starker Regen\n\nWenn Sonne: Feuer-Attacke 1,5 - Wasser-Attacke 0,5\nWenn Regen: Wasser-Attacke 1,5 - Feuer-Attacke 0,5\n\nansonsten: 1");

        lb_typ2.setText("Typ 2");

        lb_typ1.setText("Typ 1");

        combo_typ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0.5", "2", "0" }));
        combo_typ2.setToolTipText("starke Sonneneinstrahlung bzw. starker Regen\n\nWenn Sonne: Feuer-Attacke 1,5 - Wasser-Attacke 0,5\nWenn Regen: Wasser-Attacke 1,5 - Feuer-Attacke 0,5\n\nansonsten: 1");

        combo_typ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0.5", "2", "0" }));
        combo_typ1.setToolTipText("starke Sonneneinstrahlung bzw. starker Regen\n\nWenn Sonne: Feuer-Attacke 1,5 - Wasser-Attacke 0,5\nWenn Regen: Wasser-Attacke 1,5 - Feuer-Attacke 0,5\n\nansonsten: 1");

        lb_typ3.setText("Typ 3");

        combo_typ3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0.5", "2", "0" }));
        combo_typ3.setToolTipText("starke Sonneneinstrahlung bzw. starker Regen\n\nWenn Sonne: Feuer-Attacke 1,5 - Wasser-Attacke 0,5\nWenn Regen: Wasser-Attacke 1,5 - Feuer-Attacke 0,5\n\nansonsten: 1");

        javax.swing.GroupLayout p_basisinfoLayout = new javax.swing.GroupLayout(p_basisinfo);
        p_basisinfo.setLayout(p_basisinfoLayout);
        p_basisinfoLayout.setHorizontalGroup(
            p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_basisinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_level)
                    .addComponent(lb_ap)
                    .addComponent(lb_dp)
                    .addComponent(lb_z))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_basisinfoLayout.createSequentialGroup()
                        .addComponent(sld_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_levelzahl))
                    .addGroup(p_basisinfoLayout.createSequentialGroup()
                        .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_basisinfoLayout.createSequentialGroup()
                                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_dp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                    .addComponent(tf_ap, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_sr1)
                                    .addComponent(lb_stab)))
                            .addGroup(p_basisinfoLayout.createSequentialGroup()
                                .addComponent(tf_z, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lb_typ2)
                                    .addComponent(lb_typ1)
                                    .addComponent(lb_typ3))))
                        .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p_basisinfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_typ2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_stab, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_voll, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combo_typ1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_basisinfoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(combo_typ3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p_basisinfoLayout.setVerticalGroup(
            p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_basisinfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sld_level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_level, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_levelzahl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_ap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ap)
                    .addComponent(combo_voll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sr1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dp)
                    .addComponent(tf_dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_stab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_stab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_z)
                    .addComponent(tf_z, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_typ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_typ1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_typ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_typ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_basisinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_typ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_typ3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p_schadeninfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Schdeninfo"));

        cb_rh.setText("RH");

        lb_basisschaden.setText("Basisschaden");

        cb_lv.setText("LV");

        cb_ls.setText("LS");

        cb_nm.setText("NM");

        lb_angrf.setText("Angreifer-F.");

        lb_zielf.setText("Ziel-F.");

        lb_itemf.setText("Item-Faktor");
        lb_itemf.setToolTipText("");

        javax.swing.GroupLayout p_schadeninfoLayout = new javax.swing.GroupLayout(p_schadeninfo);
        p_schadeninfo.setLayout(p_schadeninfoLayout);
        p_schadeninfoLayout.setHorizontalGroup(
            p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_schadeninfoLayout.createSequentialGroup()
                .addComponent(cb_rh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_lv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_ls)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_nm)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(p_schadeninfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_schadeninfoLayout.createSequentialGroup()
                        .addComponent(lb_basisschaden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_basisschaden, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_itemf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_itemf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_schadeninfoLayout.createSequentialGroup()
                            .addComponent(lb_zielf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_zielf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, p_schadeninfoLayout.createSequentialGroup()
                            .addComponent(lb_angrf)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_angrf, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        p_schadeninfoLayout.setVerticalGroup(
            p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_schadeninfoLayout.createSequentialGroup()
                .addGroup(p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_rh)
                    .addComponent(cb_lv)
                    .addComponent(cb_ls)
                    .addComponent(cb_nm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_basisschaden)
                    .addComponent(tf_basisschaden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb_itemf)
                        .addComponent(tf_itemf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_angrf)
                    .addComponent(tf_angrf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p_schadeninfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_zielf)
                    .addComponent(tf_zielf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Berechnen"));

        btn_calc.setText("Berechnen");
        btn_calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcActionPerformed(evt);
            }
        });

        lb_erg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_calc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_erg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_calc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_erg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_schadeninfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_basisinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p_f1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_f2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p_f3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p_f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_f3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p_basisinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_schadeninfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sld_levelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sld_levelStateChanged
        lb_levelzahl.setText(""+sld_level.getValue());
    }//GEN-LAST:event_sld_levelStateChanged

    private void btn_calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcActionPerformed
        if (checkInput()){
            lb_erg.setText(""+calcDMG());
            
        }
    }//GEN-LAST:event_btn_calcActionPerformed

    public int calcDMG(){
        double dmg = sld_level.getValue() * 0.4 + 2;
        
        dmg *= calcBS();
        dmg *= ap/(50*dp);
        dmg *= calcF1();
        dmg = Math.floor(dmg) + 2; // Klammer
        
        double voll, stab, typ1, typ2, typ3;
        
        voll = Double.parseDouble(combo_voll.getSelectedItem().toString());
        stab = Double.parseDouble(combo_stab.getSelectedItem().toString());
        typ1 = Double.parseDouble(combo_typ1.getSelectedItem().toString());
        typ2 = Double.parseDouble(combo_typ2.getSelectedItem().toString());
        typ3 = Double.parseDouble(combo_typ3.getSelectedItem().toString());
        
        dmg *= voll;
        dmg *= f2;
        dmg *= calcZ();
        dmg *= stab;
        dmg *= typ1;
        dmg *= typ2;
        dmg *= typ3;
        dmg *= calcF3();
        
        return (int) Math.floor(dmg);
    }
    
    public double calcZ(){
        return (100 - z) / 100;
    }
    
    public double calcBS(){
        double basic = bs;
        
        basic *= af * zf * itf;
        
        if (cb_rh.isSelected())
            basic *= 1.5;
        if (cb_lv.isSelected())           
            basic *= 2;
        if (cb_nm.isSelected())
            basic *= 0.5;
        if (cb_ls.isSelected())
            basic *= 0.5;
        
        return basic;
    }
    
    public double calcF1(){
        
        double f1 = 1;
        
        if (cb_brt.isSelected())
            f1 *= 0.5;
        if (cb_rl.isSelected() && combo_voll.getSelectedIndex() == 0)
            f1 *= 0.5;
        if (cb_ff.isSelected())
            f1 *= 1.5;
        
        f1 *= Double.parseDouble(combo_sr.getSelectedItem().toString());
                
        
        return f1;
    }
    
    public double calcF3(){
        double f3 = 1;
        
        if (cb_fkf.isSelected())
            f3 *= 0.5;
        if (cb_eg.isSelected())
            f3 *= 1.2;
        if (cb_a.isSelected() && (combo_typ1.getSelectedIndex() == 1 || combo_typ2.getSelectedIndex() == 1))
            f3 *= 2;
        if (cb_b.isSelected())
            f3 *= 0.5;
        
        return f3;
    }
    
    public boolean checkInput(){
        if (tf_itemf.getText().equals(""))
            itf = 1;
        else {
            try {
                itf = Double.parseDouble(tf_itemf.getText()); 
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Item-Faktor: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
                return false;
            }
        }
        if (tf_f2.getText().equals(""))
            f2 = 1;
        else {
            try {
                f2 = Double.parseDouble(tf_f2.getText()); 
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "F2: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
                return false;
            }
        }
        if (tf_ap.getText().equals(""))
            ap = 1;
        else {
            try {
                ap = Double.parseDouble(tf_ap.getText()); 
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "AP: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
                return false;
            }
        }
        if (tf_dp.getText().equals(""))
            dp = 1;
        else {
            try {
                dp = Double.parseDouble(tf_dp.getText()); 
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "DP: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
                return false;
            }
        }
        if (tf_zielf.getText().equals(""))
            zf = 1;
        else {
            try {
                zf = Double.parseDouble(tf_zielf.getText()); 
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Ziel-F.: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
                return false;
            }
        }
        if (tf_angrf.getText().equals(""))
            af = 1;
        else {
            try {
                af = Double.parseDouble(tf_angrf.getText()); 
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Angreifer-F.: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
                return false;
            }
        }
        try {
            bs = Double.parseDouble(tf_basisschaden.getText()); 
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Basisschaden: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
            return false;
        }
        try {
            z = Double.parseDouble(tf_z.getText()); 
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Z: Bitte eine Zahl eingeben!\n\n"+e.getMessage());
            return false;
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calc;
    private javax.swing.JCheckBox cb_a;
    private javax.swing.JCheckBox cb_b;
    private javax.swing.JCheckBox cb_brt;
    private javax.swing.JCheckBox cb_eg;
    private javax.swing.JCheckBox cb_ff;
    private javax.swing.JCheckBox cb_fkf;
    private javax.swing.JCheckBox cb_ls;
    private javax.swing.JCheckBox cb_lv;
    private javax.swing.JCheckBox cb_nm;
    private javax.swing.JCheckBox cb_rh;
    private javax.swing.JCheckBox cb_rl;
    private javax.swing.JComboBox<String> combo_sr;
    private javax.swing.JComboBox<String> combo_stab;
    private javax.swing.JComboBox<String> combo_typ1;
    private javax.swing.JComboBox<String> combo_typ2;
    private javax.swing.JComboBox<String> combo_typ3;
    private javax.swing.JComboBox<String> combo_voll;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lb_angrf;
    private javax.swing.JLabel lb_ap;
    private javax.swing.JLabel lb_basisschaden;
    private javax.swing.JLabel lb_dp;
    private javax.swing.JLabel lb_erg;
    private javax.swing.JLabel lb_itemf;
    private javax.swing.JLabel lb_level;
    private javax.swing.JLabel lb_levelzahl;
    private javax.swing.JLabel lb_sr;
    private javax.swing.JLabel lb_sr1;
    private javax.swing.JLabel lb_stab;
    private javax.swing.JLabel lb_typ1;
    private javax.swing.JLabel lb_typ2;
    private javax.swing.JLabel lb_typ3;
    private javax.swing.JLabel lb_z;
    private javax.swing.JLabel lb_zielf;
    private javax.swing.JPanel p_basisinfo;
    private javax.swing.JPanel p_f1;
    private javax.swing.JPanel p_f2;
    private javax.swing.JPanel p_f3;
    private javax.swing.JPanel p_schadeninfo;
    private javax.swing.JSlider sld_level;
    private javax.swing.JTextField tf_angrf;
    private javax.swing.JTextField tf_ap;
    private javax.swing.JTextField tf_basisschaden;
    private javax.swing.JTextField tf_dp;
    private javax.swing.JTextField tf_f2;
    private javax.swing.JTextField tf_itemf;
    private javax.swing.JTextField tf_z;
    private javax.swing.JTextField tf_zielf;
    // End of variables declaration//GEN-END:variables
}
